name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: https://trybee-backend.railway.app/api

      - name: Create env-config.js
        run: |
          echo "// This file is dynamically generated during the build process" > dist/env-config.js
          echo "window.ENV = {" >> dist/env-config.js
          echo "  VITE_API_URL: \"https://trybee-backend.railway.app/api\"" >> dist/env-config.js
          echo "};" >> dist/env-config.js

      - name: Create CNAME
        run: echo "trybee.me" > dist/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true 